# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
sys.path.insert(0, os.path.abspath('../../'))


# -- Project information -----------------------------------------------------

project = 'BandHiC'
copyright = '2025, Weibing Wang'
author = 'Weibing Wang'

# The full version, including alpha/beta/rc tags
release = '0.1'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
# docs/conf.py

extensions = [
    'sphinx.ext.autodoc',       # 从 docstring 提取文档
    'sphinx.ext.autosummary',  # 自动生成 API 文档
    'sphinx.ext.napoleon',      # 支持 NumPy / Google 风格
    'sphinx.ext.viewcode',      # （可选）源码链接
]

autosummary_generate = True

napoleon_numpy_docstring = True
napoleon_google_docstring = False

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# -- Options for HTML output -------------------------------------------------

# 指定主题名称
html_theme = "pydata_sphinx_theme"

# 指定主题包（如果需要显式声明）
html_theme_path = [""]  # 通常可留空

# 主题选项——按需开启或调整
html_theme_options = {
    # "logo": {
    #     "image_light": "logo-light.png",   # 可选：浅色模式下的 logo
    #     "image_dark": "logo-dark.png",     # 可选：深色模式下的 logo
    # },
    # "icon_links": [                        # 可在右上角加快捷链接
    #     {
    #         "name": "GitHub",
    #         "url": "https://github.com/xdwwb/BandHiC-Master/tree/master",
    #         "icon": "fab fa-github",
    #     },
    # ],
    # "navbar_start": ["navbar-logo"],      # 导航栏左侧元素
    # "navbar_center": ["navbar-nav"],      # 导航栏中部元素
    # "navbar_end":    ["navbar-icon-links"],   # 导航栏右侧元素
    # "show_prev_next": False,              # 隐藏／显示上下篇链接
    # "navigation_depth": 2,                # 侧边栏显示深度
    # "use_edit_page_button": True,         # 在页面上显示“Edit on GitHub”按钮
    # 更多选项请参考官方文档
}

# 如果你想让侧边栏固定不滚动：
html_sidebars = {
    "**": ["sidebar-nav-bs"],
}

# 引入静态资源目录（logo、CSS 之类）
html_static_path = ["_static"]

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".


# -- Options for LaTeX output -------------------------------------------------

latex_elements = {
    'preamble': r'''
\setcounter{tocdepth}{4}
\setcounter{secnumdepth}{4}
''',
    'tableofcontents': ' ',
    'maketitle': r'''
\maketitle
\tableofcontents
\clearpage
''',
}