# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
sys.path.insert(0, os.path.abspath('../../'))
import bandhic as bh


# -- Project information -----------------------------------------------------

project = 'BandHiC'
copyright = '2025, Weibing Wang'
author = 'Weibing Wang'

# The full version, including alpha/beta/rc tags
version = bh.__version__


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
# docs/conf.py

extensions = [
    'sphinx.ext.autodoc',       # 从 docstring 提取文档
    'sphinx.ext.autosummary',  # 自动生成 API 文档
    'sphinx.ext.napoleon',      # 支持 NumPy / Google 风格
    'sphinx.ext.viewcode',      # （可选）源码链接
    'sphinx_autodoc_typehints',  # 类型提示支持
]

autosummary_generate = True

napoleon_numpy_docstring = True
napoleon_google_docstring = False

autodoc_typehints = "description"
typehints_fully_qualified = False

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# -- Options for HTML output -------------------------------------------------

html_theme = "pydata_sphinx_theme"

html_theme_path = [""]  

html_theme_options = {
    # "logo": {
    #     "image_light": "logo-light.png",
    #     "image_dark": "logo-dark.png",
    # },
    "icon_links": [
        {
            "name": "GitHub",
            "url": "https://github.com/xdwwb/BandHiC-Master/tree/main",
            "icon": "fab fa-github",
            "type": "fontawesome",
        },
    ],
    "navbar_start": ["navbar-logo"],
    "navbar_center": ["navbar-nav"],
    "navbar_end":    ["navbar-icon-links"],
    "show_prev_next": True,
    "navigation_depth": 3,
    "collapse_navigation": False,
    "show_toc_level": 3,
    "use_edit_page_button": True,
}

html_sidebars = {
    "**": ["sidebar-nav-bs"],
}

html_static_path = ["_static"]

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_context = {
    "github_user": "xdwwb", 
    "github_repo": "BandHiC-Master", 
    "github_version": "main",
}
# -- Options for LaTeX output -------------------------------------------------

latex_elements = {
    'preamble': r'''
\setcounter{tocdepth}{4}
\setcounter{secnumdepth}{4}
''',
    'tableofcontents': ' ',
    'maketitle': r'''
\maketitle
\tableofcontents
\clearpage
''',
}